import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  Container1: {
    backgroundColor: '#639CD9',
    height: '50%',
    paddingHorizontal: 15,
    flex: 1,
  },
  ContainerProducts: {
    height: '80%',
    width: '100%',
    marginBottom: 30,
    backgroundColor: '#fff',
    alignSelf: 'flex-end',
    borderRadius: 5,
    shadowColor: '#470000',
    shadowOffset: { width: 8, height: 8 },
    shadowOpacity: 1.8,
    shadowRadius: 4,
    elevation: 5,
  },
  DescriptionProducts: {
    textAlign: 'center',
    fontSize: 15,
  },
  Container: {
    backgroundColor: '#639CD9',
    height: '100%',
    paddingHorizontal: 15,
    flex: 1,
  },
  ButtonGetOut: {
    position: 'absolute',
    left: 0,
  },
  TextButtonGetOut: {
    color: '#FFFFFF',
    fontSize: 17,
    borderWidth: 1,
    padding: 3,
    borderColor: '#FFFFFF',
    borderRadius: 5,
    height: 30,
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  ViewTitle: {
    height: 40,
    marginTop: '-5%',
  },
  ViewTitle2: {
    height: 40,
    marginTop: '-20%',
  },
  Title: {
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  Title2: {
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  TitleButtonGetOut: {
    marginTop: '10%',
  },
  ButtonPlus: {
    paddingLeft: '72%',
  },
  TextButtonPlus: {
    color: '#FFFFFF',
    fontSize: 17,
    paddingTop: 10,
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  ButtonPlus2: {
    paddingLeft: '65%',
    paddingBottom: '8%',
  },
  TextButtonPlus2: {
    color: '#FFFFFF',
    fontSize: 17,
    paddingTop: 10,
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  ListCategory: {
    height: 100,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 10,
    marginTop: '-6%',
  },
  TextCards: {
    color: '#F2F3F5',
    fontSize: 13,
    marginTop: 10,
    paddingVertical: '50%',
    width: 80,
    justifyContent: 'center',
    textAlign: 'center',
  },
  Cards: {
    height: '95%',
    width: 85,
    backgroundColor: '#242E5E',
    borderRadius: 50,
    alignItems: 'center',
    paddingHorizontal: 18,
    marginHorizontal: 10,
  },
  InfoProducts: {
    width: '80%',
  },
  Zomm: {
    borderRadius: 50,
    height: '40%',
    width: '50%',
    marginTop: '15%',
    alignSelf: 'center',
  },
  Lupa: {
    width: '25%',
    marginTop: '2%',
    paddingTop: '25%',
    marginBottom: '15%',
    marginStart: '-60%',
    alignSelf: 'center',
    flexDirection: 'row',
  },
  InfoProductsText: {
    marginTop: '-40%',
    marginStart: '50%',
    width: '70%',
  },
  ViewTitle3: {
    height: 40,
    marginTop: '10%',
    backgroundColor: '#639CD9',
  },
  Title3: {
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  Text2: {
    paddingTop: '10%',
    textAlign: 'center',
    fontSize: 30,
  },
  ContainerProducts2: {
    height: '100%',
    paddingTop: '7%',
  },
  Cards2: {
    height: '73%',
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 10,
    marginRight: 15,
    shadowColor: '#470000',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1.8,
    elevation: 3,
  },
  Cards3: {
    height: '100%',
    width: '100%',
    marginBottom: '10%',
  },
  ImagemProduto2: {
    borderRadius: 20,
    height: '50%',
    width: '50%',
    marginTop: '2%',
    alignSelf: 'center',
  },
  ViewImagem2: {
    marginTop: '15%',
    height: '85%',
    width: '100%',
  },
  ViewTextCard2: {
    color: '#F2F3F5',
    textAlign: 'center',
    marginHorizontal: 10,
    marginTop: '-61%',
  },
  TextCard2: {
    color: '#000',
    fontSize: 15,
    fontWeight: 'bold',
  },
  TextCardApi: {
    color: '#000',
  },
  EditDeleteIcons2: {
    flexDirection: 'row',
    position: 'absolute',
    right: 0,
  },
  ButtonSave: {
    marginHorizontal: '39.5%',
    marginTop: '10%',
  },
  TextButtonSave: {
    color: '#FFFFFF',
    fontSize: 17,
    borderWidth: 1,
    padding: 3,
    borderColor: '#FFFFFF',
    borderRadius: 5,
    height: 30,
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  centeredView: {
    marginTop: '50%',
    marginRight: '8%',
  },
  centeredView1: {
    marginTop: '95%',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  FlowRight: {
    alignItems: 'center',
    flexDirection: 'row',
    margin: '3%',
    height: '20%',
  },
  ButtonSearch: {
    marginLeft: -20,
  },
  SearchInput: {
    fontSize: 20,
    borderWidth: 1,
    marginRight: '10%',
    borderColor: '#1c2247',
    borderRadius: 8,
    color: '#fff',
    width: '90%',
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

export default styles;
